service: notify-aws-price
provider:
  name: aws
  runtime: python3.6
  region: ap-northeast-1
  stage: dev
  environment:
    slackPostURL: "https://hooks.slack.com/services/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"
    slackChannel: "#general"

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    #dockerizePip: non-linux
    dockerizePip: false

functions:
  lambda_handler:
    name: notify-aws-price-lambda
    handler: lambda_function.lambda_handler
    memorySize: 256 # optional, in MB, default is 1024
    timeout: 30 # optional, in seconds, default is 6
    events:
      - schedule:
          rate: cron(0 15 ? * * *)
          enabled: true